// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2kEE-Cm_yKTP-vetLMRQIk97Gg7nl7Es',
    appId: '1:964614405186:web:0cd477635a6b36c5a341db',
    messagingSenderId: '964614405186',
    projectId: 'personal-expense-manager-33345',
    authDomain: 'personal-expense-manager-33345.firebaseapp.com',
    storageBucket: 'personal-expense-manager-33345.firebasestorage.app',
    measurementId: 'G-SFN6E4FJED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHqU974Ud7nF0T-Q4DdBxI2pgam9mKyzs',
    appId: '1:964614405186:android:03e3884d60daa10ea341db',
    messagingSenderId: '964614405186',
    projectId: 'personal-expense-manager-33345',
    storageBucket: 'personal-expense-manager-33345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM78CHpXEcwbD23iU_-OJz83aMZQogmPQ',
    appId: '1:964614405186:ios:da00d3e26b6ea11ea341db',
    messagingSenderId: '964614405186',
    projectId: 'personal-expense-manager-33345',
    storageBucket: 'personal-expense-manager-33345.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM78CHpXEcwbD23iU_-OJz83aMZQogmPQ',
    appId: '1:964614405186:ios:da00d3e26b6ea11ea341db',
    messagingSenderId: '964614405186',
    projectId: 'personal-expense-manager-33345',
    storageBucket: 'personal-expense-manager-33345.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2kEE-Cm_yKTP-vetLMRQIk97Gg7nl7Es',
    appId: '1:964614405186:web:6f93adebee407f9ea341db',
    messagingSenderId: '964614405186',
    projectId: 'personal-expense-manager-33345',
    authDomain: 'personal-expense-manager-33345.firebaseapp.com',
    storageBucket: 'personal-expense-manager-33345.firebasestorage.app',
    measurementId: 'G-TCT3W6C8J9',
  );
}
